name: Python application

on:
  push:
    branches: [ model-development ]
  pull_request:
    branches: [ model-development ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for MongoDB to start
      run: |
        # Wait for up to 30 seconds for MongoDB to start
        for i in {30..0}; do
          if nc -z localhost 27017; then
            echo "MongoDB is up!"
            break
          fi
          echo "Waiting for MongoDB to start..."
          sleep 1
        done
        if [ "$i" = 0 ]; then
          echo "MongoDB did not start in time."
          exit 1
        fi

    - name: Run tests
      run: |
        python -m unittest discover -s tests

    - name: Build Docker image
      run: |
        docker build -f D:\FERI\Projekti\osnove_racunalniskega_vida\Dockerfile_tests -t meduzzard/osnove-racunalniskega-vida:latest .

    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker push meduzzard/osnove-racunalniskega-vida:latest
